/home/daniel/bin/kb

/home/daniel/src/config/bin/setup-trackpoint

# start gnome keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# start services
nextcloud &
xscreensaver -no-splash &
nm-applet &
blueman-applet &
udiskie &
redshift &

# start plan9 services
fontsrv &
plumber &
factotum &

exec wmaker
