#!/bin/bash
fshell=$(finger $(whoami) | sed -n 's/.*Shell: //p' | sed 1q)
SHELL=${fshell:-$SHELL}
PLAN9=${PLAN9:-/Users/daniel/plan9}
export INSIDE_ACME=true

cd $HOME
case "$SHELL" in
*/rc)
	echo '
		if(! ~ $PLAN9/bin $path)
			path=($path $PLAN9/bin)
		$PLAN9/bin/9term -l -W600x800 &
	' | $SHELL -l
	exit 0
	;;
*/bash)
	. ~/.bash_profile
	;;
*/zsh)
	. ~/.zshrc
	;;
*)
	. ~/.profile
	;;
esac

if ! [[ :$PATH: =~ :$PLAN9/bin: ]]
then
	PATH=$PATH:$PLAN9/bin
fi

fontsrv &
$PLAN9/bin/9term -l -f /mnt/font/Menlo-Regular/13a/font -s -W600x800 &
exit 0

