#!/bin/bash

fshell=$(finger $(whoami) | sed -n 's/.*Shell: //p' | sed 1q)
SHELL=${fshell:-$SHELL}
PLAN9=${PLAN9:-/Users/daniel/plan9}

export tabstop=8
export INSIDE_ACME=true
export PAGER=nobs
export MANPAGER=nobs

cd $HOME
case "$SHELL" in
*/rc)
	echo '
		font=$lfont
		# if(! ~ $PLAN9/bin $path)
		#	path=($path $PLAN9/bin)
		$PLAN9/bin/sam -a -W2048x1024 &
	' | $SHELL -l
	exit 0
	;;
*/bash)
	. ~/.bash_profile
	;;
*/zsh)
	source ~/.zshrc
	;;
*)
	. ~/.profile
	;;
esac

if ! [[ :$PATH: =~ :$PLAN9/bin: ]]
then
	PATH=$PATH:$PLAN9/bin
fi

if hash skhd 2>/dev/null; then
	echo 'sam: starting skhd' >> /tmp/samlog
	skhd &
else
	echo 'sam: skhd not in $PATH, skipping...' >> /tmp/samlog
fi

$PLAN9/bin/plumber &
$PLAN9/bin/fontsrv &
$PLAN9/bin/sam -a &

exit 0

