# defaults
export EDITOR='vi'
export VISUAL=$EDITOR
export GIT_EDITOR=$EDITOR
export USER_DIR=/Users/daniel

# constants
export NEXTCLOUD=$USER_DIR/Nextcloud
export MARTIN=$USER_DIR/work/martin-bidder
export PERSONAL=$USER_DIR/personal
export CFG=$USER_DIR/cfg
export BIN_DIR=$HOME/bin
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export ICLOUDDIR="$USER_DIR/Library/Mobile\ Documents/com~apple~CloudDocs"

# FZF
export FZF_DEFAULT_COMMAND='rg --files'

# source external scipts
source $NEXTCLOUD/secrets/secrets.sh
source $MARTIN/shell/aliases.sh
source $MARTIN/shell/functions.sh

# Navigation
alias ".."="cd .."
alias h="cd ~"
alias mar="cd $MARTIN"
alias per="cd $PERSONAL"
alias cfg="cd $CFG"
alias dow="cd ~/Downloads"
alias notes="cd ~/notes"
alias drop="cd ~/Dropbox"
alias next="cd $NEXTCLOUD"
alias learn="cd $HOME/exercism"
alias brewup="brew update; brew upgrade; brew cleanup; brew doctor"
alias refresh="source ~/.zshrc"
alias icloud="cd $ICLOUDDIR"
alias gs="git status"
alias gp="git push"

# unix defaults
alias cp="cp -i"                                                # Confirm before overwriting something
alias df='df -h'                                                # Human-readable sizes
alias free='free -m'                                            # Show sizes in MB

# Tmux
alias t="tmux -2 -u"
alias tat="tmux attach -t"
alias ts="tmux ls"
alias tk="tmux kill-session -t"

l() { ls $* }
g() { git $* }
gc() { git commit -am $* }
pip() { pip3 $* }

gcloudconfig() {
	gcloud config configurations activate $1
	gcloud info | grep Project
}

proj() {
	gcloud config configurations activate $1
	gcloud info | grep Project
}

#
# Prompt
#
autoload -U colors && colors
export PS1="%{$fg[blue]%}%c%{$reset_color%} %% "  # current directory name

#
# Keybindings
#
bindkey -e

#
# $PATH
#

# ensure homebrew path is set
eval "$(/opt/homebrew/bin/brew shellenv)"

#
# Set paths for homebrew installed programs
#
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

# Monorepo
export PATH=$PATH:$MARTIN/bin

# Home Bin
export PATH=$PATH:$BIN_DIR/sh
export PATH=$PATH:$BIN_DIR/amd64

export PATH=$PATH:$USER_DIR/.local/bin

# Google Cloud SDK
if [ -f '/Users/daniel/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/daniel/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '/Users/daniel/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/daniel/google-cloud-sdk/completion.zsh.inc'; fi

# FZF
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Rust
source "$HOME/.cargo/env"

# Go
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin:

[ -f "/Users/daniel/.ghcup/env" ] && source "/Users/daniel/.ghcup/env" # ghcup-env

