# defaults
export EDITOR='vi'
export VISUAL=$EDITOR
export GIT_EDITOR=$EDITOR
export USER_DIR=/Users/daniel

# constants
export NEXTCLOUD=$USER_DIR/Nextcloud
export MARTIN=$USER_DIR/work/martin-bidder
export PERSONAL=$USER_DIR/personal
export CFG=$USER_DIR/cfg
export BIN_DIR=$HOME/bin
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
# export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64

# FZF
export FZF_DEFAULT_COMMAND='rg --files'

# source external scipts
source $NEXTCLOUD/secrets/secrets.sh
source $MARTIN/shell/aliases.sh
source $MARTIN/shell/functions.sh

# Navigation
alias ".."="cd .."
alias h="cd ~"
alias mar="cd $MARTIN"
alias per="cd $PERSONAL"
alias cfg="cd $CFG"
alias dow="cd ~/Downloads"
alias notes="cd ~/notes"
alias drop="cd ~/Dropbox"
alias next="cd $NEXTCLOUD"
alias learn="cd $HOME/exercism"
alias brewup="brew update; brew upgrade; brew cleanup; brew doctor"
alias gs="git status"
alias gp="git push"

# unix defaults
alias cp="cp -i"                                                # Confirm before overwriting something
alias df='df -h'                                                # Human-readable sizes
alias free='free -m'                                            # Show sizes in MB

# Tmux
alias t="tmux -2 -u"
alias tat="tmux attach -t"
alias ts="tmux ls"
alias tk="tmux kill-session -t"

g() {
	git $*
}

gc() {
	git commit -am $*
}

pip() {
	pip3 $*
}

gcloudconfig() {
	gcloud config configurations activate $1
	gcloud info | grep Project
}

proj() {
	gcloud config configurations activate $1
	gcloud info | grep Project
}


# BASE16_SHELL="$HOME/.config/base16-shell/"
# [ -n "$PS1" ] && \
#     [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
#         eval "$("$BASE16_SHELL/profile_helper.sh")" 
# # set colorscheme
# base16_default-dark

# ensure homebrew path is set
eval "$(/opt/homebrew/bin/brew shellenv)"

# Monorepo
export PATH=$PATH:$MARTIN/bin

# Home Bin
export PATH=$PATH:$BIN_DIR/sh
export PATH=$PATH:$BIN_DIR/amd64

# Google Cloud SDK
if [ -f '/Users/daniel/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/daniel/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '/Users/daniel/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/daniel/google-cloud-sdk/completion.zsh.inc'; fi

# FZF
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Rust
source "$HOME/.cargo/env"

# Go
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin:

#
# Prompt
#
autoload -U colors && colors
export PS1="%{$fg[blue]%}%c%{$reset_color%} %% "  # current directory name

